FROM openanolis/anolisos:8.6 as OS

ENV TZ="Asia/Shanghai" \
    LANG="zh_CN.UTF-8" \
    LC_ALL="C"

RUN set -eu; \
    yum install -y python38; \
    yum clean all; \
    ln -sf /usr/bin/python3 /usr/bin/python; \
    ln -sf /usr/bin/pip3 /usr/bin/pip; \
    python3 -m pip install --upgrade --root-user-action ignore pip; \
    python3 -c "import sysconfig; print(sysconfig.get_config_var('CONFIG_ARGS'))"; \
    pip cache purge; \
    rm -rf /var/cache/yum/*; \
    rm -rf /root/.cache; \
    rm -rf /tmp/*

FROM scratch

COPY \
    --from=OS / /

LABEL \
    AUTHOR="IVAN DU" \
    DATE="2024-08-28" \
    VERSION="1.0.0" \
    PYTHON_VERSION="3.8.17"

ENV TZ="Asia/Shanghai" \
    LANG="zh_CN.UTF-8" \
    LC_ALL="C"